
services:
  db:
    image: postgres:16 # Скачивает образ postgres, пароль postgres
    container_name: todo-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    healthcheck: # Нужно, чтобы бд раньше бэкенда поднялась
      test: ["CMD-SHELL", "pg_isready -U postgres -d app_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: todo-backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "3000:80" # nginx слушает 80 порт   